### ISSUE TITLE
SerialServer Import Failure

### ISSUE THREAD

**Issue by chrisguikema** [seL4/camkes-tool#119]
When attempting to build an x86 VM with a SerialServer connection, I get this error when invoking the `init-build.sh` script:

```
ERROR:CAmkES:/host/projects/global-components/components/SerialServer/SerialServer.camkes:49:19:         HARDWARE_SERIAL_COMPOSITION
ERROR:CAmkES:                                                                                                      ^
ERROR:CAmkES:unknown reference to 'Serial'
```

The issue is due to defining a `Serial.camkes` file for each COM port on x86 (which was a good change). I validated that the Import paths were being handled properly. (Debug print is mine).

```
Serial port com1 selected.
-- path: /host/projects/camkes-tool/components/plat/pc99/plat/components/serial_com1
```

My fix is to rename the `pc99/plat/components/serial_comX/Serial.camkes` files to `SerialCom.camkes` and `import <SerialCom.camkes>`

```
diff --git a/components/plat/pc99/plat/serial.camkes b/components/plat/pc99/plat/serial.camkes
index 44025ff..b1b680a 100644
--- a/components/plat/pc99/plat/serial.camkes
+++ b/components/plat/pc99/plat/serial.camkes
@@ -4,4 +4,4 @@
  * SPDX-License-Identifier: BSD-2-Clause
  */
 
-import <Serial.camkes>;
+import <SerialCom.camkes>;
```

I'm unsure if you'll be able to replicate the issue, as it may be related to how my Macbook handles file paths, but I'm hoping the fix is simple enough that you can just pull it in

**Comment by axel-h** [comment]
So, are you running into a file name clash because several `Serial.camkes` exists and CAmkES is picking the wrong one? That would explain the `unknown reference to 'Serial'` message then, because the definition is missing. We have `<camkes-tool>/components/arch/arm/arch/serial.camkes` and `camkes-tool/components/plat/pc99/plat/components/serial_com1/Serial.camkes`, but one has a upper case "S" the other a lower case "s", so these should be different files. I can't find any other file with that name. Do you have another one locally?

**Comment by chrisguikema** [comment]
As far as I can tell that is the problem.

I am compiling everything in a ARM based Docker container on an M1 MacBook. I wonder if my filesystem is case insensitive, so its treating `Serial.camkes` and `serial.camkes` as the same file. Its the only explanation I can think of, because I had a colleague compile the same application from the same state with a Docker container on an Ubuntu system and he didn't have issues.

I do understand I'm a guinea pig here, since I'm compiling in a non-standard environment (everything else seems to work!), but I am doing my best to give feedback so others don't have the same issues.

**Comment by chrisguikema** [comment]
For reference, this change also works, which points to the case-sensitive v. case-insensitive problem:

```
diff --git a/components/plat/pc99/plat/serial.camkes b/components/plat/pc99/plat/serial.camkes
index 44025ff..75483c8 100644
--- a/components/plat/pc99/plat/serial.camkes
+++ b/components/plat/pc99/plat/serial.camkes
@@ -4,4 +4,4 @@
  * SPDX-License-Identifier: BSD-2-Clause
  */
 
-import <Serial.camkes>;
+import <test/Serial.camkes>;
```

And adding a `test` subdirectory in `components/plat/pc99/plat/components/serial_com1/`

To me, renaming the files to add some differentiation is best, but if you'd prefer the subdirectory solution, that would also work.
