### ISSUE TITLE
Old link to Visual CAmkES wiki

### ISSUE THREAD

**Issue by sheepybloke** [seL4/camkes-tool#12]
Hey guys,

This is a really small thing, but the link to the Visual CAmkES wiki is broken. Is it supposed to point to this page? https://wiki.sel4.systems/VisualCAmkES

Thanks!

**Comment by stevebob** [comment]
Thanks for pointing that out. I've fixed the link internally. It should be pushed out to github shortly (in a day or so). I'll close this when that happens.

**Comment by stevebob** [comment]
Fixed
