### ISSUE TITLE
Error message for unsupported connection is misleading

### ISSUE THREAD

**Issue by jtdaugherty** [seL4/camkes-tool#2]
Given the `helloworld` assembly in http://sel4.systems/CAmkES/README.pml, i.e.,

```
assembly {
    composition {
        component Hello h;
        component Client c;
        connection seL4RPC conn(from c.iface, to h.inf);
    }
}
```

if you get the `from` and `to` mixed up (like I did the first time, because I didn't just copy and paste), i.e.,

```
        connection seL4RPC conn(from h.inf, to c.iface);
```

then the resulting error message is vague and doesn't suggest that this was the mistake:

```
Unresolved references in input specification:
 .../seL4/apps/helloworld/helloworld.camkes:11:'inf' of type Interface
 .../seL4/apps/helloworld/helloworld.camkes:11:'iface' of type Interface
```

**Comment by Smattr** [comment]
I don't remember if I explored this precisely when refactoring the CAmkES parser, but I believe on the "next" branch this is now handled in a more user-friendly way during so-called "freezing" ([camkes/ast/objects.py:474-549](https://github.com/seL4/camkes-tool/blob/next/camkes/ast/objects.py#L474-L549)). The complexity of back porting this logic to "master" is probably not worth it, but hopefully this pain point is only temporary until "next" becomes "master" (he says, conscious of this issue having been open for two years...).
