### ISSUE TITLE
seL4/ci-actions/style fails in template

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-tool#42]
in https://github.com/axel-h/camkes-tool/runs/1192932657 seL4/ci-actions/style fails in template camkes/templates/camkes-gen.cmake
```
CRITICAL:root:['/home/runner/work/camkes-tool/camkes-tool/camkes-top-level.cmake', '/home/runner/work/camkes-tool/camkes-tool/CMakeLists.txt', '/home/runner/work/camkes-tool/camkes-tool/libsel4camkes/CMakeLists.txt', '/home/runner/work/camkes-tool/camkes-tool/components/plat/pc99/plat/CMakeLists.txt', '/home/runner/work/camkes-tool/camkes-tool/components/components.cmake', '/home/runner/work/camkes-tool/camkes-tool/libcamkescakeml/CMakeLists.txt', '/home/runner/work/camkes-tool/camkes-tool/Findcamkes-tool.cmake', '/home/runner/work/camkes-tool/camkes-tool/camkes/templates/camkes-gen.cmake', '/home/runner/work/camkes-tool/camkes-tool/camkes/templates/templates.cmake', '/home/runner/work/camkes-tool/camkes-tool/camkes.cmake'] failed with error code 1
'While processing /home/runner/work/camkes-tool/camkes-tool/camkes/templates/camkes-gen.cmake
Traceback (most recent call last):
  File "/home/runner/.local/bin/cmake-format", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.6/site-packages/cmake_format/__main__.py", line 421, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/home/runner/.local/lib/python3.6/site-packages/cmake_format/__main__.py", line 110, in process_file
    parse_tree = parser.parse(tokens, config.fn_spec)
  File "/home/runner/.local/lib/python3.6/site-packages/cmake_format/parser.py", line 608, in parse
    return consume_body(tokens, cmdspec)
  File "/home/runner/.local/lib/python3.6/site-packages/cmake_format/parser.py", line 592, in consume_body
    tokens[0].begin.line, tokens[0].begin.col))
AssertionError: Unexpected UNQUOTED_LITERAL token at 30:0
```
I assume the problem is that this is template processing code is not hidden in a a CMake comment, so it is considered CMake code for the style checker. But it is indeed invalid CMake code. 
```
/*- set instances = composition.instances -*/
/*- set connections = composition.connections -*/
```
Maybe the style check must run after the a dummy run of the template processor has simply removed all template code?

**Comment by kent-mcleod** [comment]
This file should be excluded from the style runs due to the style filter (https://github.com/axel-h/camkes-tool/blob/master/.stylefilter#L17).

**Comment by lsf37** [comment]
It's possible that the style filter path doesn't work properly, because the path setup is different between Bamboo and GitHub. I've had problems with that before. Basically one instance sees relative paths from the repo root, and the other instance sees absolute paths, and so the matching doesn't work as expected if the patter is relative.

I'll have a look if that can be made more robust.

**Comment by lsf37** [comment]
I believe this should now be fixed. @axel-h can you confirm?

**Comment by lsf37** [comment]
(actually, sorry one more PR to merge, the one in seL4/ci-actions#43)

**Comment by lsf37** [comment]
Ok, now it's actually ready.

**Comment by axel-h** [comment]
@lsf37: looks better now, I get https://github.com/axel-h/camkes-tool/runs/1839221539?check_suite_focus=true
I'm stil trying to figure out what the github actually tell me here, because the seem to complain about a commit that I can't find. But that's out of the scope of this issue.
