### ISSUE TITLE
Misleading error message: "Multiple CAmkES applications selected. Only a single application can be built at once.  Stop."

### ISSUE THREAD

**Issue by agacek** [seL4/camkes-tool#5]
When no camkes applications are selected, the error message is still

`Multiple CAmkES applications selected. Only a single application can be built at once.  Stop.`

Which is misleading.

**Comment by agacek** [comment]
Seems like it should be an easy fix to

  https://github.com/seL4/camkes-tool/blob/master/toplevel.mk#L71

But I can't do it myself since Rockwell hasn't signed off on the code release form.

**Comment by Smattr** [comment]
I don't have commit access anymore, but this was fixed in bacfebce on the "next" branch. If someone from Data61 wants to cherry pick the relevant hunk into "master" I think that should address this issue.

**Comment by agacek** [comment]
As @Smattr said, this is fixed in CAmkES next.
