### ISSUE TITLE
group component

### ISSUE THREAD

**Issue by Hamed-Kh18** [seL4/camkes-tool#51]
Hello

This program is supposed called a echo with client and write "hello world". i need uses as "Single Address Space Components (Groups)".

`assembly {
    composition {
        group group_test{
            component Echo echo;
            component Client client;
        }

        connection seL4DirectCall p(from group_test.client.a, to group_test.echo.a);
    }
}`

This method is performed in x86_64 platform. But not on the "imx7" platform. Is this possible for the imx7 platform?

**Comment by axel-h** [comment]
The i.MX7 platform has build issues and is currently not supported actively, see for example https://github.com/seL4/seL4/issues/254
If you have access to an i.MX7 platform, support for making it work is appreciated. However, it seems you issue might be generic for all ARM platforms?

**Comment by Hamed-Kh18** [comment]
Thanks.I need this method because of the limited memory space. Do you have no way to solve this problem?
